### ISSUE TITLE
Feedback: Please ensure comment format is consistent

### ISSUE THREAD

**Issue by 9600baud** [Henrywis/Capstone-project#1]
https://github.com/Henrywis/Capstone-project/blob/87b31aef5e0c97a2590ff73414376ea6d4a99233/iRecruit-ui/src/App.jsx#L29

For comments, its usually best to stick to a consistent format.  Either have it:

```
// This is my comment
const someCodeHere = 1; 
```

or

```
const someCodeHere = 1; // This is another comment
```

**Comment by Henrywis** [comment]
Noted! Thank you very much for the feedback! I will put that to practice henceforth.
