### ISSUE TITLE
Do not commit / push commented out code

### ISSUE THREAD

**Issue by 9600baud** [Henrywis/Capstone-project#2]
https://github.com/Henrywis/Capstone-project/blob/87b31aef5e0c97a2590ff73414376ea6d4a99233/iRecruit-ui/src/App.jsx#L3-L4

We should avoid pushing or committing code that is no longer used / old test code.  Github needs to remain a clean place

**Comment by Henrywis** [comment]
Noted

**Comment by Henrywis** [comment]
I am more conscious moving on. Thanks for the feedback!
